package com.macro.mall.tiny.mbg.model;

import java.io.Serializable;

public class UmsDepartment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_department.id
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_department.name
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_department.number
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_department
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_department.id
     *
     * @return the value of ums_department.id
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_department.id
     *
     * @param id the value for ums_department.id
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_department.name
     *
     * @return the value of ums_department.name
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_department.name
     *
     * @param name the value for ums_department.name
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_department.number
     *
     * @return the value of ums_department.number
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_department.number
     *
     * @param number the value for ums_department.number
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_department
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", number=").append(number);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}