package com.macro.mall.tiny.mbg.mapper;

import com.macro.mall.tiny.mbg.model.UmsRole;
import com.macro.mall.tiny.mbg.model.UmsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    long countByExample(UmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int deleteByExample(UmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int insert(UmsRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int insertSelective(UmsRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    List<UmsRole> selectByExample(UmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    UmsRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("row") UmsRole row, @Param("example") UmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByExample(@Param("row") UmsRole row, @Param("example") UmsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(UmsRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_role
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByPrimaryKey(UmsRole row);
}