package com.macro.mall.tiny.mbg.mapper;

import com.macro.mall.tiny.mbg.model.UmsResource;
import com.macro.mall.tiny.mbg.model.UmsResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    long countByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int deleteByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int insert(UmsResource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int insertSelective(UmsResource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    List<UmsResource> selectByExample(UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    UmsResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("row") UmsResource row, @Param("example") UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByExample(@Param("row") UmsResource row, @Param("example") UmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(UmsResource row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_resource
     *
     * @mbg.generated Thu Aug 01 16:44:44 GMT+08:00 2024
     */
    int updateByPrimaryKey(UmsResource row);
}